export const CONFIG = {
  SERVER_URL: import.meta.env.VITE_SERVER_URL,
  NODE_ENV: import.meta.env.VITE_NODE_ENV,
  DEV_TOOLS: import.meta.env.VITE_DEV_TOOLS,
  CLIENT_URL_DEV: import.meta.env.VITE_CLIENT_URL_DEV,
  PRODUCTS_URL: import.meta.env.VITE_PRODUCTS_URL,
  PRODUCT_DETAILS_URL: import.meta.env.VITE_PRODUCT_DETAILS_URL,
  CART_URL: '/cart',
  USERS_URL: import.meta.env.VITE_USERS_URL,
  ORDERS_URL: import.meta.env.VITE_ORDERS_URL,
  BLOG_URL: import.meta.env.VITE_BLOG_URL,
  TECH_URL: import.meta.env.VITE_TECH_URL,
  CHECKOUT_AUTH_CHECK: import.meta.env.VITE_CHECKOUT_AUTH_CHECK,
  PAYPAL_URL: import.meta.env.VITE_PAYPAL_URL,
}
