import {
  PATH_HOME,
  PATH_TECH,
  PATH_AUTH,
  PATH_BAG,
  PATH_ORDERS,
  PATH_KICKS,
  PATH_USERS,
  PATH_ACCOUNT,
  PATH_TALKS,
  PATH_PRODUCTS,
  CONFIG,
} from './config-global'

export const BASE_URL =
  CONFIG.NODE_ENV === 'development' ? CONFIG.SERVER_URL : ''

export const DEV_TOOLS =
  CONFIG.NODE_ENV === 'development' ? CONFIG.DEV_TOOLS : false

// Server ROUTES
export const PRODUCTS_URL = CONFIG.PRODUCTS_URL
export const PRODUCT_DETAILS_URL = CONFIG.PRODUCT_DETAILS_URL
export const USERS_URL = CONFIG.USERS_URL
export const ORDERS_URL = CONFIG.ORDERS_URL
export const TECH_URL = CONFIG.TECH_URL
export const BLOG_URL = CONFIG.BLOG_URL
export const CHECKOUT_AUTH_CHECK = CONFIG.CHECKOUT_AUTH_CHECK
export const PAYPAL_URL = CONFIG.PAYPAL_URL

// Client ROUTES
export const CLIENT = {
  // @root: HOME
  HOME_URL: PATH_HOME.ROOT,

  // @root: PRODUCTS
  PRODUCTS_URL: PATH_PRODUCTS.ROOT,
  PRODUCT_URL: PATH_PRODUCTS.PRODUCT,

  // @root: TECH
  TECH_URL: PATH_TECH.ROOT,

  // @root: TALKS
  TALKS_URL: PATH_TALKS.ROOT,

  // @root: KICKS
  KICKS_URL: PATH_KICKS.ROOT,

  // @root: BAG
  BAG_URL: PATH_BAG.ROOT,
  SHIPPING_URL: PATH_BAG.SHIPPING,
  PAYMENT_URL: PATH_BAG.PAYMENT,
  BAGCONFIRM_URL: PATH_BAG.CONFIRM,
  AUTH_REDIRECT: PATH_BAG.AUTH_REDIRECT,

  // @root: ORDERS
  ORDERS_URL: PATH_ORDERS.ROOT,
  ORDER_URL: PATH_ORDERS.ORDER,
  HISTORY_URL: PATH_ORDERS.HISTORY,

  // @root: USERS
  USERS_URL: PATH_USERS.ROOT,

  // @root: ACCOUNT
  ACCOUNT_URL: PATH_ACCOUNT.ROOT,

  // @root: AUTH
  AUTH_URL: PATH_AUTH.ROOT,
  LOGIN_URL: PATH_AUTH.LOGIN,
  LOGOUT_URL: PATH_AUTH.LOGOUT,
  REGISTER_URL: PATH_AUTH.REGISTER,
  LOGIN_REDIRECT: PATH_AUTH.LOGIN_REDIRECT,
  REGISTER_REDIRECT: PATH_AUTH.REGISTER_REDIRECT,
  FORGOT_PASSWORD: PATH_AUTH.FORGOT_PASSWORD,

  // @root: boundary
  NOT_FOUND_URL: CONFIG.CLIENT_NOT_FOUND_URL,
}
